ansible_admin_authorized_key: "{{ lookup('file', '/tmp/telegraf-setup-playbook/ubuntu_ansible.pub') }}"

ansible_admin_groups:
  - sudo

ubuntu_required_packages:
  - ca-certificates
  - curl
  - gnupg
  - auditd
  - osquery
  - tailscale
  - prometheus-node-exporter
  - fluent-bit
  - docker.io

tailscale_authkey: ""
tailscale_hostname: "{{ inventory_hostname }}"

loki_host: archlinux-control-plane
loki_port: 3100
loki_uri: /loki/api/v1/push

splunk_hec_host: archlinux-control-plane
splunk_hec_port: 8088
splunk_hec_token: ""
splunk_hec_index: security
splunk_hec_sourcetype: vm_security
splunk_hec_tls: true
